/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Catalogo;
import clases.Usuario;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import utilidades.Notificaciones;

/**
 *
 * @author excz010715
 */
public class MDIPrincipal extends javax.swing.JFrame {

    private jpfAdministracion objAdministracion = new jpfAdministracion();
    private jpfInventario objInventario = new jpfInventario();
    private jpfPagos objPagos = new jpfPagos();
    private jpfVentas objVentas = new jpfVentas();
    private jpfLibro objLibro = new jpfLibro();
    private jpfReportes objReportes = new jpfReportes();

    private ArrayList<Catalogo> catalogos;

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        catalogos = new ArrayList<>();
        initComponents();
        inicializarFormularios();
    }

    public void inicializarFormularios() {
        configurarPantalla(jifAdministracion, objAdministracion, "Administracion");
        configurarPantalla(jifInventario, objInventario, "Inventario");
        configurarPantalla(jifPagos, objPagos, "Pagos");
        configurarPantalla(jifVentas, objVentas, "Ventas");
        configurarPantalla(jifLibro, objLibro, "Libro diario");
        configurarPantalla(jifReportes, objReportes, "Reportes");

        /*jifAdministracion.setContentPane(objAdministracion);
        objAdministracion.setSize(300, 300);
        jifAdministracion.setSize(300, 300);
        jifAdministracion.setClosable(true);

        jifInventario.setContentPane(objInventario);
        objInventario.setSize(300, 300);
        jifInventario.setSize(300, 300);
        jifInventario.setClosable(true);*/
    }

    public void configurarPantalla(JInternalFrame jif, JPanel panel, String titulo) {
        //setExtendedState(MAXIMIZED_BOTH);
        jif.setContentPane(panel);
        panel.setSize(300, 300);

        //jif.setMaximum(true);
        jif.setTitle(titulo);
        jif.setResizable(true);
        jif.setMaximizable(true);

        jif.setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        btnAdministracion = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnventas = new javax.swing.JButton();
        btnLibroDiario = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jifAdministracion = new javax.swing.JInternalFrame();
        jifInventario = new javax.swing.JInternalFrame();
        jifPagos = new javax.swing.JInternalFrame();
        jifVentas = new javax.swing.JInternalFrame();
        jifLibro = new javax.swing.JInternalFrame();
        jifReportes = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdministracion.setText("Administración");
        btnAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministracionActionPerformed(evt);
            }
        });
        desktopPane.add(btnAdministracion);
        btnAdministracion.setBounds(710, 190, 130, 40);

        btnInventario.setText("Inventario");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        desktopPane.add(btnInventario);
        btnInventario.setBounds(160, 120, 130, 40);

        btnPagos.setText("Pagos");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        desktopPane.add(btnPagos);
        btnPagos.setBounds(160, 190, 130, 40);

        btnventas.setText("Ventas");
        btnventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasActionPerformed(evt);
            }
        });
        desktopPane.add(btnventas);
        btnventas.setBounds(160, 260, 130, 40);

        btnLibroDiario.setText("Libro Diario");
        btnLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroDiarioActionPerformed(evt);
            }
        });
        desktopPane.add(btnLibroDiario);
        btnLibroDiario.setBounds(160, 330, 130, 40);

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        desktopPane.add(btnReportes);
        btnReportes.setBounds(710, 120, 130, 40);

        jifAdministracion.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifAdministracion.setVisible(false);

        javax.swing.GroupLayout jifAdministracionLayout = new javax.swing.GroupLayout(jifAdministracion.getContentPane());
        jifAdministracion.getContentPane().setLayout(jifAdministracionLayout);
        jifAdministracionLayout.setHorizontalGroup(
            jifAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifAdministracionLayout.setVerticalGroup(
            jifAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifAdministracion);
        jifAdministracion.setBounds(40, 40, 1120, 530);

        jifInventario.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifInventario.setVisible(false);

        javax.swing.GroupLayout jifInventarioLayout = new javax.swing.GroupLayout(jifInventario.getContentPane());
        jifInventario.getContentPane().setLayout(jifInventarioLayout);
        jifInventarioLayout.setHorizontalGroup(
            jifInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifInventarioLayout.setVerticalGroup(
            jifInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifInventario);
        jifInventario.setBounds(390, 230, 22, 40);

        jifPagos.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifPagos.setVisible(false);

        javax.swing.GroupLayout jifPagosLayout = new javax.swing.GroupLayout(jifPagos.getContentPane());
        jifPagos.getContentPane().setLayout(jifPagosLayout);
        jifPagosLayout.setHorizontalGroup(
            jifPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifPagosLayout.setVerticalGroup(
            jifPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifPagos);
        jifPagos.setBounds(390, 230, 22, 40);

        jifVentas.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifVentas.setVisible(false);

        javax.swing.GroupLayout jifVentasLayout = new javax.swing.GroupLayout(jifVentas.getContentPane());
        jifVentas.getContentPane().setLayout(jifVentasLayout);
        jifVentasLayout.setHorizontalGroup(
            jifVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifVentasLayout.setVerticalGroup(
            jifVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifVentas);
        jifVentas.setBounds(390, 230, 22, 40);

        jifLibro.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifLibro.setVisible(false);

        javax.swing.GroupLayout jifLibroLayout = new javax.swing.GroupLayout(jifLibro.getContentPane());
        jifLibro.getContentPane().setLayout(jifLibroLayout);
        jifLibroLayout.setHorizontalGroup(
            jifLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifLibroLayout.setVerticalGroup(
            jifLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifLibro);
        jifLibro.setBounds(390, 230, 22, 40);

        jifReportes.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifReportes.setVisible(false);

        javax.swing.GroupLayout jifReportesLayout = new javax.swing.GroupLayout(jifReportes.getContentPane());
        jifReportes.getContentPane().setLayout(jifReportesLayout);
        jifReportesLayout.setHorizontalGroup(
            jifReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifReportesLayout.setVerticalGroup(
            jifReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifReportes);
        jifReportes.setBounds(390, 230, 22, 40);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        jMenuItem1.setText("Logout");
        fileMenu.add(jMenuItem1);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        if (Notificaciones.mensajeConfirmacion("Salir", "Esta seguro que desea salir del sistema?")) {
            System.exit(0);
        }

    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        jifInventario.setVisible(true);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministracionActionPerformed
        jifAdministracion.setVisible(true);
    }//GEN-LAST:event_btnAdministracionActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
        jifPagos.setVisible(true);
    }//GEN-LAST:event_btnPagosActionPerformed

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
        jifVentas.setVisible(true);
    }//GEN-LAST:event_btnventasActionPerformed

    private void btnLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroDiarioActionPerformed
        jifLibro.setVisible(true);
    }//GEN-LAST:event_btnLibroDiarioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        jifReportes.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAdministracion;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLibroDiario;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnventas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JInternalFrame jifAdministracion;
    private javax.swing.JInternalFrame jifInventario;
    private javax.swing.JInternalFrame jifLibro;
    private javax.swing.JInternalFrame jifPagos;
    private javax.swing.JInternalFrame jifReportes;
    private javax.swing.JInternalFrame jifVentas;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
